const form=document.getElementById('resourceForm'),rows=document.getElementById('resourceRows'),empty=document.getElementById('empty'),status=document.getElementById('status'),uploadBtn=document.getElementById('uploadBtn');
const labels={'project-work':'Undergraduate Project Work','dissertation':'Dissertation','assessor':'Assessment Reports'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=d=>d?new Date(d).toLocaleString():'Built-in';
function size(n){n=Number(n||0);if(!n)return '';if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`;}
async function load(){const res=await fetch('/api/developer/resources');const data=await res.json().catch(()=>[]);if(!res.ok)throw new Error(data.error||'Could not load resources.');document.getElementById('resourceCount').textContent=data.length;rows.innerHTML=data.map((r,i)=>`<tr><td>${i+1}</td><td><span class="resource-title">${esc(r.title)}${r.builtIn?'<span class="builtin">BUILT-IN</span>':''}</span>${r.description?`<span class="resource-desc">${esc(r.description)}</span>`:''}</td><td>${esc(r.originalName)}${r.size?`<br><small>${esc(size(r.size))}</small>`:''}</td><td>${(r.portals||[]).map(p=>`<span class="tag">${esc(labels[p]||p)}</span>`).join('')}</td><td>${esc(fmt(r.uploadedAt))}</td><td><a class="download" href="${esc(r.downloadUrl)}">Download</a>${r.canDelete?` <button class="danger" type="button" onclick="removeResource('${esc(r.id)}')">Delete</button>`:''}</td></tr>`).join('');empty.hidden=data.length>0;}
form.addEventListener('submit',async e=>{e.preventDefault();const selected=[...form.querySelectorAll('input[name="portals"]:checked')];if(!selected.length){status.className='status bad';status.textContent='Select at least one submission portal.';return;}const old=uploadBtn.textContent;uploadBtn.disabled=true;uploadBtn.textContent='Uploading…';status.textContent='';status.className='status';try{const fd=new FormData(form);const res=await fetch('/api/developer/resources',{method:'POST',body:fd});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Upload failed.');form.reset();status.className='status ok';status.textContent='Resource uploaded and published successfully.';await load();}catch(e){status.className='status bad';status.textContent=e.message||'Upload failed.';}finally{uploadBtn.disabled=false;uploadBtn.textContent=old;}});
window.removeResource=async id=>{if(!confirm('Delete this resource from the public submission portals? This cannot be undone.'))return;try{const res=await fetch(`/api/developer/resources/${encodeURIComponent(id)}`,{method:'DELETE'});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Could not delete the resource.');await load();}catch(e){alert(e.message||'Could not delete the resource.');}};
document.getElementById('refreshBtn').onclick=()=>load().catch(e=>alert(e.message));
load().catch(e=>{status.className='status bad';status.textContent=e.message||'Could not load resources.';});
