const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const portalLabels={'project-work':'Undergraduate Project Work','field-experience':'Field Experience and Teaching Practice','dissertation':'Dissertation','assessor':'Assessment/Vetting Reports','payroll':'Payroll Portal','auditor':"Auditor's Portal"};
const deptLabels={'education':'Education','business':'Business','arts-social-sciences':'Arts & Social Sciences','science-mathematics':'Science & Mathematics'};
const unitLabels={'student-support':'Student Support Services','student-records':'Student Records Management','college-registrar':'College Registrar','provost':'Provost','directorate-education-business':'Directorate of Education and Business Studies','directorate-arts-stem':'Directorate of Arts and STEM Studies','examinations':'Examinations Unit','payroll':'Payroll','auditor':"Auditor's Portal",'regional-administrator':'Regional Administrators','coordinator':'Centre Coordinators','quality-assurance':'Quality Assurance Unit','college-finance':'College Finance Officer','admissions':'Admissions Unit','stores':'Stores Unit'};
unitLabels['registration-officer']='Registration Officer Portal';
const roleLabels={viewer:'Viewer',officer:'Officer',administrator:'Administrator'};
const functionalUnitAccess=document.querySelector('#adminForm fieldset');
if(functionalUnitAccess&&!functionalUnitAccess.querySelector('input[value="registration-officer"]'))functionalUnitAccess.insertAdjacentHTML('beforeend','<label class="check"><input type="checkbox" name="units" value="registration-officer"> Registration Officer Portal</label>');
const fmt=d=>d?new Date(d).toLocaleString():'Built-in';
function size(n){n=Number(n||0);if(!n)return '';if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`;}
async function getJson(url,opt){const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d;}

// v27: developer/system-admin sections are tabbed to reduce page clutter.
const devTabs=[...document.querySelectorAll('.developer-tab')],devPanels=[...document.querySelectorAll('.developer-panel')];
function activateDeveloperTab(tab){const valid=devTabs.map(b=>b.dataset.devTab);if(!valid.includes(tab))tab='resources';devTabs.forEach(b=>b.classList.toggle('active',b.dataset.devTab===tab));devPanels.forEach(p=>p.classList.toggle('hidden',p.dataset.devPanel!==tab));history.replaceState(null,'',`${location.pathname}${location.search}#${tab}`);}
devTabs.forEach(b=>b.addEventListener('click',()=>activateDeveloperTab(b.dataset.devTab)));

let previewOptions={departments:[],staffUnits:[],profiles:[],accounts:[]};
function previewSectionsText(sections){return (sections||[]).map(x=>portalLabels[x]||x).join(', ')||'No sections';}
function updatePreviewAccountOptions(){
  const department=document.getElementById('previewDepartment')?.value||'';
  const select=document.getElementById('previewAccount');if(!select)return;
  const list=(previewOptions.accounts||[]).filter(a=>a.active!==false&&(a.departments||[]).includes(department));
  select.innerHTML='<option value="">Select an administrator</option>'+list.map(a=>`<option value="${esc(a.id)}">${esc(a.name||a.username)} · ${esc(roleLabels[a.role]||a.role)} · ${esc(previewSectionsText(a.sections))}</option>`).join('');
}
function updatePreviewProfileHelp(){
  const id=document.getElementById('previewProfile')?.value||'';
  const p=(previewOptions.profiles||[]).find(x=>x.id===id);
  const help=document.getElementById('previewProfileHelp');if(help)help.textContent=p?`${roleLabels[p.role]||p.role}: ${previewSectionsText(p.sections)}.`:'';
}
function updatePreviewMode(){
  const mode=document.getElementById('previewMode')?.value||'profile';
  document.getElementById('previewProfileBlock')?.classList.toggle('hidden',mode!=='profile');
  document.getElementById('previewAccountBlock')?.classList.toggle('hidden',mode!=='account');
}
async function loadPreviewOptions(){
  previewOptions=await getJson('/api/developer/preview-options');
  const department=document.getElementById('previewDepartment'),operationsDepartment=document.getElementById('operationsDepartment'),profile=document.getElementById('previewProfile'),staffUnit=document.getElementById('staffPreviewUnit');
  if(department){department.innerHTML=(previewOptions.departments||[]).map(d=>`<option value="${esc(d.slug)}">${esc(d.name)}</option>`).join('');}
  if(operationsDepartment){operationsDepartment.innerHTML=(previewOptions.departments||[]).map(d=>`<option value="${esc(d.slug)}" ${d.slug==='education'?'selected':''}>${esc(d.name)}</option>`).join('');}
  if(profile){profile.innerHTML=(previewOptions.profiles||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.label)} · ${esc(roleLabels[p.role]||p.role)}</option>`).join('');}
  if(staffUnit){staffUnit.innerHTML=(previewOptions.staffUnits||[]).map(unit=>`<option value="${esc(unit.id)}">${esc(unit.label)}</option>`).join('');}
  updatePreviewAccountOptions();updatePreviewProfileHelp();updatePreviewMode();
}

async function launchOperationsPortal(destination){
  const department=document.getElementById('operationsDepartment')?.value||'education',status=document.getElementById('operationsLaunchStatus');
  const button=document.getElementById(destination==='payroll'?'openPayrollPortal':'openAuditorPortal');
  const target=window.open('about:blank','_blank');button.disabled=true;status.className='status';status.textContent=`Opening ${destination==='payroll'?'Payroll':"Auditor's"} Portal…`;
  try{
    const data=await getJson('/api/developer/preview-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'profile',department,destination,profileId:'operations-officer'})});
    status.className='status ok';status.textContent=`${destination==='payroll'?'Payroll':"Auditor's"} Portal opened with access to all departments.`;
    if(target)target.location.href=data.redirect;else location.href=data.redirect;
  }catch(error){if(target)target.close();status.className='status bad';status.textContent=error.message;}finally{button.disabled=false;}
}
document.getElementById('openPayrollPortal')?.addEventListener('click',()=>launchOperationsPortal('payroll'));
document.getElementById('openAuditorPortal')?.addEventListener('click',()=>launchOperationsPortal('auditor'));
document.getElementById('openStaffPreview')?.addEventListener('click',async()=>{const unit=document.getElementById('staffPreviewUnit')?.value||'',button=document.getElementById('openStaffPreview'),status=document.getElementById('staffPreviewStatus');const target=window.open('about:blank','_blank');button.disabled=true;status.className='status';status.textContent='Creating secure developer preview session…';try{const data=await getJson('/api/developer/staff-preview-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unit})});status.className='status ok';status.textContent=`Opening ${data.previewLabel} without a staff login.`;if(target)target.location.href=data.redirect;else location.href=data.redirect;}catch(error){if(target)target.close();status.className='status bad';status.textContent=error.message||'Could not open the functional-unit portal.';}finally{button.disabled=false;}});

async function loadResources(){const data=await getJson('/api/developer/resources');document.getElementById('resourceCount').textContent=data.length;document.getElementById('resourceRows').innerHTML=data.map((r,i)=>`<tr><td>${i+1}</td><td><span class="resource-title">${esc(r.title)}${r.builtIn?'<span class="builtin">BUILT-IN</span>':''}</span>${r.description?`<span class="resource-desc">${esc(r.description)}</span>`:''}</td><td>${esc(r.originalName)}${r.size?`<br><small>${esc(size(r.size))}</small>`:''}</td><td>${(r.departments||[]).length?(r.departments||[]).map(d=>`<span class="tag">${esc(deptLabels[d]||d)}</span>`).join(''):'<span class="tag">All departments</span>'}</td><td>${(r.portals||[]).map(p=>`<span class="tag">${esc(portalLabels[p]||p)}</span>`).join('')}</td><td>${esc(fmt(r.uploadedAt))}</td><td><a class="download" href="${esc(r.downloadUrl)}">Download</a>${r.canDelete?` <button class="danger" onclick="removeResource('${esc(r.id)}')">Delete</button>`:''}</td></tr>`).join('');}
function accountState(a){if(!a.active)return {label:'Disabled',cls:'inactive-pill',detail:''};if(a.passwordSet)return {label:'Ready',cls:'active-pill',detail:a.passwordSetAt?`Password set ${fmt(a.passwordSetAt)}`:''};if(a.invitationEmailStatus==='failed')return {label:'Email failed',cls:'failed-pill',detail:a.invitationLastError||''};if(a.invitationExpired)return {label:'Invite expired',cls:'expired-pill',detail:a.invitationExpiresAt?`Expired ${fmt(a.invitationExpiresAt)}`:''};if(a.invitationEmailStatus==='sent')return {label:'Awaiting setup',cls:'pending-pill',detail:a.invitationExpiresAt?`Expires ${fmt(a.invitationExpiresAt)}`:''};return {label:'Invitation pending',cls:'pending-pill',detail:''};}
async function loadAdmins(){const data=await getJson('/api/developer/admin-users');previewOptions.accounts=data;document.getElementById('adminCount').textContent=data.length;document.getElementById('adminRows').innerHTML=data.map((a,i)=>{const state=accountState(a),inviteLabel=a.passwordSet?'Send Password Reset':'Resend Invite',inviteButton=a.email?`<button class="secondary compact" onclick="sendAdminInvite('${esc(a.id)}')">${inviteLabel}</button>`:'',previewButton=a.active&&(a.departments||[]).length?`<button class="download compact" onclick="previewAdminAccount('${esc(a.id)}')">Preview</button>`:'';return `<tr><td>${i+1}</td><td><strong>${esc(a.name)}</strong><br><small>${esc(a.email||'')}</small><br><small>Username: ${esc(a.username)}</small></td><td><span class="role role-${esc(a.role)}">${esc(roleLabels[a.role]||a.role)}</span></td><td>${(a.units||[]).map(x=>`<span class="tag">${esc(unitLabels[x]||x)}</span>`).join('')||'<span class="tag">None</span>'}</td><td>${(a.departments||[]).map(x=>`<span class="tag">${esc(deptLabels[x]||x)}</span>`).join('')||'<span class="tag">None</span>'}</td><td>${(a.hodDepartments||[]).map(x=>`<span class="tag">${esc(deptLabels[x]||x)}</span>`).join('')||'<span class="tag">None</span>'}<br><small>${a.hasHodSignature?'Signature stored':'No signature'}</small></td><td>${(a.sections||[]).map(x=>`<span class="tag">${esc(portalLabels[x]||x)}</span>`).join('')||'<span class="tag">None</span>'}</td><td><span class="${state.cls}">${esc(state.label)}</span>${state.detail?`<span class="status-detail">${esc(state.detail)}</span>`:''}</td><td><div class="button-row">${previewButton}${inviteButton}${a.role==='administrator'&&a.departments?.length?`<button class="secondary compact" onclick="setHodAuthority('${esc(a.id)}')">HoD Authority</button>`:''}<button class="secondary compact" onclick="toggleAdmin('${esc(a.id)}',${a.active?'false':'true'})">${a.active?'Disable':'Enable'}</button><button class="danger compact" onclick="deleteAdmin('${esc(a.id)}')">Delete</button></div></td></tr>`;}).join('');}
async function loadCentres(){const data=await getJson('/api/developer/study-centres'),catalogue=data.departments||{},states=data.centreStates||{};document.getElementById('centreCount').textContent=data.total??Object.values(catalogue).reduce((n,list)=>n+(Array.isArray(list)?list.length:0),0);document.getElementById('centreTags').innerHTML=Object.keys(deptLabels).map(slug=>{const list=(Array.isArray(catalogue[slug])?catalogue[slug]:[]).slice().sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true,sensitivity:'base'}));return `<section class="centre-group"><h4>${esc(deptLabels[slug])} <span>${list.length}</span></h4>${list.length?`<div class="centre-item-list">${list.map(c=>{const enabled=states[String(c).toLowerCase()]!==false;return `<span class="centre-tag ${enabled?'':'centre-disabled'}"><span>${esc(c)}</span>${enabled?'':'<small>Disabled</small>'}</span>`}).join('')}</div>`:'<div class="centre-empty">No centres assigned to this department.</div>'}</section>`}).join('');}
async function loadCentreDirectory(){const data=await getJson('/api/developer/study-centre-directory'),list=data.centres||[];document.getElementById('directoryCount').textContent=data.count??list.length;document.getElementById('centreDirectoryRows').innerHTML=list.map((c,i)=>`<tr class="${c.enabled===false?'centre-disabled-row':''}"><td>${i+1}</td><td>${esc(c.id||'')}</td><td><strong>${esc(c.code)}</strong></td><td>${esc(c.name)}</td><td>${(c.departments||[]).map(slug=>`<span class="tag">${esc(deptLabels[slug]||slug)}</span>`).join('')||'<span class="tag">Unassigned</span>'}</td><td><span class="${c.enabled===false?'inactive-pill':'active-pill'}">${c.enabled===false?'Disabled':'Enabled'}</span></td><td><button class="secondary compact" type="button" onclick="toggleCentreStatus('${encodeURIComponent(c.code)}',${c.enabled===false?'true':'false'})">${c.enabled===false?'Enable':'Disable'}</button></td></tr>`).join('')||'<tr><td colspan="7">No centre codes are configured.</td></tr>';}
async function loadPortalSettings(){const d=await getJson('/api/developer/portal-settings');document.getElementById('fieldExperienceClaimRequirement').value=d.fieldExperienceClaimFormRequired?'required':'optional';}
let chatbotLibrary={responses:[],analytics:{},categories:[]};
function chatbotStatusLabel(status){return {published:'Published',draft:'Draft',retired:'Retired'}[status]||status}
function renderChatbotResponses(){
  const search=String(document.getElementById('chatbotResponseSearch')?.value||'').trim().toLowerCase(),status=document.getElementById('chatbotResponseFilter')?.value||'all';
  const list=(chatbotLibrary.responses||[]).filter(item=>(status==='all'||item.status===status)&&(!search||[item.title,item.responsibleUnit,item.categoryKey,...(item.keywords||[]),...(item.alternativeQuestions||[])].join(' ').toLowerCase().includes(search)));
  document.getElementById('chatbotResponseRows').innerHTML=list.map((item,index)=>`<tr><td>${index+1}</td><td><div class="chatbot-response-summary"><strong>${esc(item.title)}</strong><small>${esc((item.alternativeQuestions||[]).slice(0,2).join(' · '))}</small><small>Keywords: ${esc((item.keywords||[]).join(', ')||'None')}</small></div></td><td>${esc((chatbotLibrary.categories||[]).find(category=>category.id===item.categoryKey)?.label||item.categoryKey)}<br><small>${esc(item.responsibleUnit)}</small></td><td>${esc(({en:'English',tw:'Twi',fr:'French'})[item.language]||item.language)}</td><td><span class="chatbot-status chatbot-status-${esc(item.status)}">${esc(chatbotStatusLabel(item.status))}</span><br><small>v${esc(item.version||1)}</small></td><td><div class="chatbot-feedback"><span>${Number(item.usageCount||0)} answer(s)</span><small>${Number(item.helpfulCount||0)} helpful · ${Number(item.notHelpfulCount||0)} not helpful</small></div></td><td>${esc(fmt(item.updatedAt))}<br><small>${esc(item.updatedBy||'')}</small></td><td><div class="button-row"><button class="secondary compact" type="button" onclick="editChatbotResponse('${esc(item.id)}')">Edit</button>${item.status==='published'?`<button class="secondary compact" type="button" onclick="setChatbotResponseStatus('${esc(item.id)}','retired')">Retire</button>`:`<button class="download compact" type="button" onclick="setChatbotResponseStatus('${esc(item.id)}','published')">Publish</button>`}${item.status!=='published'?`<button class="danger compact" type="button" onclick="deleteChatbotResponse('${esc(item.id)}')">Delete</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No chatbot responses match the selected filter.</td></tr>';
}
function renderChatbotUnanswered(){const list=chatbotLibrary.analytics?.unanswered||[];document.getElementById('chatbotUnansweredRows').innerHTML=list.map((item,index)=>`<tr><td>${index+1}</td><td class="chatbot-unanswered-question">${esc(item.question)}</td><td>${esc((chatbotLibrary.categories||[]).find(category=>category.id===item.categoryKey)?.label||item.categoryKey||'Not selected')}</td><td>${esc(({en:'English',tw:'Twi',fr:'French'})[item.language]||item.language)}</td><td>${esc(fmt(item.createdAt))}</td><td><div class="button-row"><button class="download compact" type="button" onclick="useUnansweredQuestion('${esc(item.id)}')">Create response</button><button class="secondary compact" type="button" onclick="dismissUnansweredQuestion('${esc(item.id)}')">Mark reviewed</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No unanswered questions are awaiting review.</td></tr>'}
async function loadChatbotResponses(){chatbotLibrary=await getJson('/api/developer/chatbot-responses');const metrics=chatbotLibrary.analytics||{};document.getElementById('chatbotResponseCount').textContent=metrics.total||0;document.getElementById('chatbotPublishedCount').textContent=metrics.published||0;document.getElementById('chatbotDraftCount').textContent=metrics.draft||0;document.getElementById('chatbotRetiredCount').textContent=metrics.retired||0;document.getElementById('chatbotUnansweredCount').textContent=metrics.unansweredCount||0;renderChatbotResponses();renderChatbotUnanswered()}
function clearChatbotResponseForm(){const form=document.getElementById('chatbotResponseForm');form?.reset();document.getElementById('chatbotResponseId').value='';document.getElementById('chatbotSortOrder').value='100';document.getElementById('saveChatbotResponse').textContent='Save Response';document.getElementById('chatbotResponseStatus').className='status';document.getElementById('chatbotResponseStatus').textContent=''}
async function loadAll(){await Promise.all([loadResources(),loadAdmins(),loadCentres(),loadCentreDirectory(),loadPortalSettings(),loadPreviewOptions(),loadChatbotResponses()]);}

const previewForm=document.getElementById('previewForm'),previewStatus=document.getElementById('previewStatus'),launchPreviewBtn=document.getElementById('launchPreviewBtn');
document.getElementById('previewDepartment')?.addEventListener('change',updatePreviewAccountOptions);
document.getElementById('previewMode')?.addEventListener('change',updatePreviewMode);
document.getElementById('previewProfile')?.addEventListener('change',updatePreviewProfileHelp);
previewForm?.addEventListener('submit',async e=>{
  e.preventDefault();
  const mode=document.getElementById('previewMode').value,department=document.getElementById('previewDepartment').value,destination=document.getElementById('previewDestination').value;
  const payload={mode,department,destination};
  if(mode==='account'){payload.accountId=document.getElementById('previewAccount').value;if(!payload.accountId){previewStatus.className='status bad';previewStatus.textContent='Select an existing administrator account.';return;}}
  else payload.profileId=document.getElementById('previewProfile').value;
  const previewWindow=window.open('about:blank','_blank');
  launchPreviewBtn.disabled=true;previewStatus.className='status';previewStatus.textContent='Creating secure developer preview session…';
  try{
    const d=await getJson('/api/developer/preview-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
    previewStatus.className='status ok';previewStatus.textContent=`Preview ready as ${d.previewLabel}. Opening portal…`;
    if(previewWindow)previewWindow.location.href=d.redirect;else location.href=d.redirect;
  }catch(err){if(previewWindow)previewWindow.close();previewStatus.className='status bad';previewStatus.textContent=err.message;}finally{launchPreviewBtn.disabled=false;}
});

const resourceForm=document.getElementById('resourceForm'),resourceStatus=document.getElementById('resourceStatus'),uploadBtn=document.getElementById('uploadBtn');
resourceForm.addEventListener('submit',async e=>{e.preventDefault();if(!resourceForm.querySelector('input[name="departments"]:checked')){resourceStatus.className='status bad';resourceStatus.textContent='Select at least one department.';return;}if(!resourceForm.querySelector('input[name="portals"]:checked')){resourceStatus.className='status bad';resourceStatus.textContent='Select at least one portal.';return;}uploadBtn.disabled=true;try{await getJson('/api/developer/resources',{method:'POST',body:new FormData(resourceForm)});resourceForm.reset();resourceStatus.className='status ok';resourceStatus.textContent='Resource published.';await loadResources();}catch(e){resourceStatus.className='status bad';resourceStatus.textContent=e.message;}finally{uploadBtn.disabled=false;}});
window.removeResource=async id=>{if(!confirm('Delete this resource?'))return;try{await getJson(`/api/developer/resources/${encodeURIComponent(id)}`,{method:'DELETE'});await loadResources();}catch(e){alert(e.message);}};

const adminForm=document.getElementById('adminForm'),adminStatus=document.getElementById('adminStatus'),createAdminBtn=document.getElementById('createAdminBtn');
adminForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(adminForm),payload={firstName:fd.get('firstName'),middleName:fd.get('middleName'),lastName:fd.get('lastName'),email:fd.get('email'),username:fd.get('username'),role:fd.get('role'),units:fd.getAll('units'),departments:fd.getAll('departments'),hodDepartments:fd.getAll('hodDepartments'),sections:fd.getAll('sections')};if(!payload.units.length&&!payload.departments.length){adminStatus.className='status bad';adminStatus.textContent='Select at least one functional unit or department.';return;}createAdminBtn.disabled=true;try{const d=await getJson('/api/developer/admin-users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});adminForm.reset();adminStatus.className=d.emailSent?'status ok':'status warn';adminStatus.textContent=d.emailSent?'Staff account created and a one-time password setup link was emailed.':(d.warning||'Staff account created, but the invitation email was not sent.');await loadAdmins();}catch(e){adminStatus.className='status bad';adminStatus.textContent=e.message;}finally{createAdminBtn.disabled=false;}});
window.setHodAuthority=async id=>{const account=(previewOptions.accounts||[]).find(item=>item.id===id);if(!account)return;const allowed=account.departments||[],current=(account.hodDepartments||[]).join(',');const entered=prompt(`Enter HoD department codes separated by commas. Allowed: ${allowed.join(', ')}. Leave blank to remove authority.`,current);if(entered===null)return;const hodDepartments=entered.split(',').map(value=>value.trim()).filter(value=>allowed.includes(value));try{await getJson(`/api/developer/admin-users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({hodDepartments})});await loadAdmins()}catch(error){alert(error.message)}};
window.sendAdminInvite=async id=>{if(!confirm('Send a new one-time password setup link to this administrator? Any earlier setup link will stop working.'))return;try{await getJson(`/api/developer/admin-users/${id}/resend-invitation`,{method:'POST'});adminStatus.className='status ok';adminStatus.textContent='A new one-time password setup link was emailed.';await loadAdmins();}catch(e){adminStatus.className='status bad';adminStatus.textContent=e.message;await loadAdmins().catch(()=>{});}};
window.deleteAdmin=async id=>{if(!confirm('Delete this administrator account?'))return;try{await getJson(`/api/developer/admin-users/${id}`,{method:'DELETE'});await loadAdmins();}catch(e){alert(e.message);}};
window.toggleAdmin=async(id,active)=>{try{await getJson(`/api/developer/admin-users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active})});await loadAdmins();}catch(e){alert(e.message);}};
window.previewAdminAccount=id=>{const account=(previewOptions.accounts||[]).find(a=>a.id===id);if(!account)return alert('Refresh the page and try again.');activateDeveloperTab('preview');document.getElementById('previewMode').value='account';updatePreviewMode();const department=(account.departments||[])[0]||'';if(department)document.getElementById('previewDepartment').value=department;updatePreviewAccountOptions();document.getElementById('previewAccount').value=id;const sections=account.sections||[];document.getElementById('previewDestination').value=sections.some(x=>['project-work','field-experience','dissertation','assessor'].includes(x))?'admin':sections.includes('payroll')?'payroll':sections.includes('auditor')?'auditor':'admin';document.getElementById('previewStatus').className='status';document.getElementById('previewStatus').textContent=`Ready to preview ${account.name||account.username} without their password.`;};

const singleCentreForm=document.getElementById('singleCentreForm'),singleCentreStatus=document.getElementById('singleCentreStatus'),addSingleCentreBtn=document.getElementById('addSingleCentreBtn');
singleCentreForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(singleCentreForm),payload={id:fd.get('id'),code:fd.get('code'),name:fd.get('name'),departments:fd.getAll('departments')};if(!payload.departments.length){singleCentreStatus.className='status bad';singleCentreStatus.textContent='Select at least one department.';return;}addSingleCentreBtn.disabled=true;try{const d=await getJson('/api/developer/study-centres/item',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});singleCentreForm.reset();singleCentreStatus.className='status ok';singleCentreStatus.textContent=`${d.name} saved, enabled and assigned without replacing existing lists.`;await Promise.all([loadCentres(),loadCentreDirectory()]);}catch(e){singleCentreStatus.className='status bad';singleCentreStatus.textContent=e.message;}finally{addSingleCentreBtn.disabled=false;}});

const centreForm=document.getElementById('centreForm'),centreStatus=document.getElementById('centreStatus'),uploadCentresBtn=document.getElementById('uploadCentresBtn');
centreForm.addEventListener('submit',async e=>{e.preventDefault();if(!centreForm.querySelector('input[name="departments"]:checked')){centreStatus.className='status bad';centreStatus.textContent='Select at least one department for this centre list.';return;}if(!confirm('Replace the complete centre list for the selected department(s) with this CSV?'))return;uploadCentresBtn.disabled=true;try{const d=await getJson('/api/developer/study-centres',{method:'POST',body:new FormData(centreForm)});centreForm.reset();centreStatus.className='status ok';centreStatus.textContent=`Published ${d.count} study centres for ${d.departments.length} department${d.departments.length===1?'':'s'}.`;await loadCentres();}catch(e){centreStatus.className='status bad';centreStatus.textContent=e.message;}finally{uploadCentresBtn.disabled=false;}});
document.getElementById('resetCentres').onclick=async()=>{if(!confirm('Restore the approved study-centre list for all four departments? Disabled status in the code directory is unchanged.'))return;try{const d=await getJson('/api/developer/study-centres/reset',{method:'POST'});centreStatus.className='status ok';centreStatus.textContent=`Restored ${d.count} approved centres to all departments.`;await loadCentres();}catch(e){centreStatus.className='status bad';centreStatus.textContent=e.message;}};

const singleCentreDirectoryForm=document.getElementById('singleCentreDirectoryForm'),singleCentreDirectoryStatus=document.getElementById('singleCentreDirectoryStatus'),saveSingleCentreDirectoryBtn=document.getElementById('saveSingleCentreDirectoryBtn');
singleCentreDirectoryForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(singleCentreDirectoryForm),payload={id:fd.get('id'),code:fd.get('code'),name:fd.get('name'),departments:fd.getAll('departments')};saveSingleCentreDirectoryBtn.disabled=true;try{const d=await getJson('/api/developer/study-centre-directory/item',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});singleCentreDirectoryForm.reset();singleCentreDirectoryStatus.className='status ok';singleCentreDirectoryStatus.textContent=d.updated?'Centre record updated.':'Centre record added.';await Promise.all([loadCentreDirectory(),loadCentres()]);}catch(e){singleCentreDirectoryStatus.className='status bad';singleCentreDirectoryStatus.textContent=e.message;}finally{saveSingleCentreDirectoryBtn.disabled=false;}});
window.toggleCentreStatus=async(encodedCode,enabled)=>{const code=decodeURIComponent(encodedCode);if(!confirm(`${enabled?'Enable':'Disable'} centre ${code}? ${enabled?'It will return to its assigned public department lists.':'It will be hidden from public department lists without deleting its record, code or assignments.'}`))return;try{const d=await getJson(`/api/developer/study-centre-directory/${encodeURIComponent(code)}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});singleCentreDirectoryStatus.className='status ok';singleCentreDirectoryStatus.textContent=d.message;await Promise.all([loadCentreDirectory(),loadCentres()]);}catch(e){singleCentreDirectoryStatus.className='status bad';singleCentreDirectoryStatus.textContent=e.message;}};

const centreDirectoryForm=document.getElementById('centreDirectoryForm'),centreDirectoryStatus=document.getElementById('centreDirectoryStatus'),uploadCentreDirectoryBtn=document.getElementById('uploadCentreDirectoryBtn');
centreDirectoryForm.addEventListener('submit',async e=>{e.preventDefault();if(!centreDirectoryForm.querySelector('input[name="departments"]:checked')){centreDirectoryStatus.className='status bad';centreDirectoryStatus.textContent='Select at least one department for the imported centres.';return;}if(!confirm('Replace the current study-centre code directory and publish all imported centres to the selected departments?'))return;uploadCentreDirectoryBtn.disabled=true;try{const d=await getJson('/api/developer/study-centre-directory',{method:'POST',body:new FormData(centreDirectoryForm)});centreDirectoryForm.reset();centreDirectoryStatus.className='status ok';centreDirectoryStatus.textContent=`Updated ${d.count} centre-code records and ${d.departments.length} department list${d.departments.length===1?'':'s'}.`;await Promise.all([loadCentreDirectory(),loadCentres()]);}catch(e){centreDirectoryStatus.className='status bad';centreDirectoryStatus.textContent=e.message;}finally{uploadCentreDirectoryBtn.disabled=false;}});
document.getElementById('resetCentreDirectory').onclick=async()=>{if(!confirm('Restore the approved study-centre code directory and republish its centres to all four departments?'))return;try{const d=await getJson('/api/developer/study-centre-directory/reset',{method:'POST'});centreDirectoryStatus.className='status ok';centreDirectoryStatus.textContent=`Restored ${d.count} approved centre-code records and all department lists.`;await Promise.all([loadCentreDirectory(),loadCentres()]);}catch(e){centreDirectoryStatus.className='status bad';centreDirectoryStatus.textContent=e.message;}};

const portalSettingsForm=document.getElementById('portalSettingsForm'),portalSettingsStatus=document.getElementById('portalSettingsStatus'),savePortalSettingsBtn=document.getElementById('savePortalSettingsBtn');
portalSettingsForm.addEventListener('submit',async e=>{e.preventDefault();savePortalSettingsBtn.disabled=true;try{const required=document.getElementById('fieldExperienceClaimRequirement').value==='required';const d=await getJson('/api/developer/portal-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({fieldExperienceClaimFormRequired:required})});portalSettingsStatus.className='status ok';portalSettingsStatus.textContent=`Field Experience and Teaching Practice Claim Form is now ${d.fieldExperienceClaimFormRequired?'Compulsory':'Optional'}.`;}catch(e){portalSettingsStatus.className='status bad';portalSettingsStatus.textContent=e.message;}finally{savePortalSettingsBtn.disabled=false;}});

const chatbotResponseForm=document.getElementById('chatbotResponseForm'),chatbotResponseStatus=document.getElementById('chatbotResponseStatus'),saveChatbotResponse=document.getElementById('saveChatbotResponse');
chatbotResponseForm?.addEventListener('submit',async event=>{event.preventDefault();if(!chatbotResponseForm.reportValidity())return;const form=new FormData(chatbotResponseForm),id=String(form.get('id')||''),payload={title:form.get('title'),categoryKey:form.get('categoryKey'),matterType:form.get('matterType'),alternativeQuestions:form.get('alternativeQuestions'),keywords:form.get('keywords'),answer:form.get('answer'),responsibleUnit:form.get('responsibleUnit'),language:form.get('language'),status:form.get('status'),actionLabel:form.get('actionLabel'),actionUrl:form.get('actionUrl'),sortOrder:Number(form.get('sortOrder')||100),quickQuestion:Boolean(form.get('quickQuestion'))};saveChatbotResponse.disabled=true;chatbotResponseStatus.className='status';chatbotResponseStatus.textContent='Saving response…';try{await getJson(id?`/api/developer/chatbot-responses/${encodeURIComponent(id)}`:'/api/developer/chatbot-responses',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});clearChatbotResponseForm();chatbotResponseStatus.className='status ok';chatbotResponseStatus.textContent=id?'Response updated.':'Response created.';await loadChatbotResponses()}catch(error){chatbotResponseStatus.className='status bad';chatbotResponseStatus.textContent=error.message}finally{saveChatbotResponse.disabled=false}});
document.getElementById('clearChatbotResponse')?.addEventListener('click',clearChatbotResponseForm);
document.getElementById('chatbotResponseSearch')?.addEventListener('input',renderChatbotResponses);
document.getElementById('chatbotResponseFilter')?.addEventListener('change',renderChatbotResponses);
document.getElementById('chatbotCategory')?.addEventListener('change',event=>{const category=(chatbotLibrary.categories||[]).find(item=>item.id===event.target.value),unit=document.getElementById('chatbotResponsibleUnit'),type=document.getElementById('chatbotMatterType'),url=document.getElementById('chatbotActionUrl');if(category&&unit&&!unit.value)unit.value=category.owner||'';if(type&&event.target.value==='incomplete-result')type.value='complaint';if(url&&!url.value)url.value=`/student-support.html?type=${encodeURIComponent(type?.value||'service-request')}&category=${encodeURIComponent(event.target.value)}`});
window.editChatbotResponse=id=>{const item=(chatbotLibrary.responses||[]).find(response=>response.id===id);if(!item)return;activateDeveloperTab('chatbot');document.getElementById('chatbotResponseId').value=item.id;document.getElementById('chatbotTitle').value=item.title||'';document.getElementById('chatbotCategory').value=item.categoryKey||'general';document.getElementById('chatbotMatterType').value=item.matterType||'service-request';document.getElementById('chatbotAlternatives').value=(item.alternativeQuestions||[]).join('\n');document.getElementById('chatbotKeywords').value=(item.keywords||[]).join(', ');document.getElementById('chatbotAnswer').value=item.answer||'';document.getElementById('chatbotResponsibleUnit').value=item.responsibleUnit||'';document.getElementById('chatbotLanguage').value=item.language||'en';document.getElementById('chatbotStatus').value=item.status||'draft';document.getElementById('chatbotActionLabel').value=item.actionLabel||'';document.getElementById('chatbotActionUrl').value=item.actionUrl||'';document.getElementById('chatbotSortOrder').value=Number(item.sortOrder||100);document.getElementById('chatbotQuickQuestion').checked=Boolean(item.quickQuestion);document.getElementById('saveChatbotResponse').textContent='Update Response';chatbotResponseForm.scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('chatbotTitle').focus()};
window.setChatbotResponseStatus=async(id,status)=>{if(!confirm(`${status==='published'?'Publish':'Retire'} this chatbot response?`))return;try{await getJson(`/api/developer/chatbot-responses/${encodeURIComponent(id)}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await loadChatbotResponses()}catch(error){alert(error.message)}};
window.deleteChatbotResponse=async id=>{if(!confirm('Delete this draft or retired chatbot response and its edit history?'))return;try{await getJson(`/api/developer/chatbot-responses/${encodeURIComponent(id)}`,{method:'DELETE'});await loadChatbotResponses()}catch(error){alert(error.message)}};
window.useUnansweredQuestion=id=>{const item=(chatbotLibrary.analytics?.unanswered||[]).find(question=>question.id===id);if(!item)return;clearChatbotResponseForm();document.getElementById('chatbotTitle').value=item.question||'';document.getElementById('chatbotAlternatives').value=item.question||'';document.getElementById('chatbotCategory').value=item.categoryKey||'general';document.getElementById('chatbotLanguage').value=item.language||'en';document.getElementById('chatbotStatus').value='draft';document.getElementById('chatbotCategory').dispatchEvent(new Event('change'));chatbotResponseForm.scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('chatbotAnswer').focus()};
window.dismissUnansweredQuestion=async id=>{if(!confirm('Mark this unanswered question as reviewed and remove it from the queue?'))return;try{await getJson(`/api/developer/chatbot-unanswered/${encodeURIComponent(id)}`,{method:'DELETE'});await loadChatbotResponses()}catch(error){alert(error.message)}};
const chatbotImportForm=document.getElementById('chatbotImportForm'),chatbotImportStatus=document.getElementById('chatbotImportStatus'),importChatbotResponses=document.getElementById('importChatbotResponses');
chatbotImportForm?.addEventListener('submit',async event=>{event.preventDefault();if(!chatbotImportForm.reportValidity())return;importChatbotResponses.disabled=true;chatbotImportStatus.className='status';chatbotImportStatus.textContent='Importing responses…';try{const data=await getJson('/api/developer/chatbot-responses/import',{method:'POST',body:new FormData(chatbotImportForm)});chatbotImportForm.reset();chatbotImportStatus.className=data.errors?.length?'status warn':'status ok';chatbotImportStatus.textContent=`Imported ${data.imported} and updated ${data.updated} response(s).${data.errors?.length?` ${data.errors.length} row(s) need attention: ${data.errors.slice(0,3).join(' ')}`:''}`;await loadChatbotResponses()}catch(error){chatbotImportStatus.className='status bad';chatbotImportStatus.textContent=error.message}finally{importChatbotResponses.disabled=false}});

document.getElementById('refreshResources').onclick=()=>loadResources().catch(e=>alert(e.message));
document.getElementById('refreshAdmins').onclick=()=>loadAdmins().catch(e=>alert(e.message));
document.getElementById('refreshChatbotResponses').onclick=()=>loadChatbotResponses().catch(e=>alert(e.message));
loadAll().then(()=>activateDeveloperTab((location.hash||'').replace('#','')||'resources')).catch(e=>{console.error(e);resourceStatus.className='status bad';resourceStatus.textContent=e.message||'Could not load developer data.';});
