const department=location.pathname.split('/').filter(Boolean)[1]||'';let rows=[];let identity={};const roleRank={viewer:1,officer:2,administrator:3};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=v=>{if(!v)return '';try{return new Date(v).toLocaleString()}catch{return v}};
async function get(url,opts){const r=await fetch(url,opts),d=await r.json().catch(()=>({}));if(r.status===401){location.href=`/admin-login.html?department=${encodeURIComponent(department)}&next=${encodeURIComponent(location.pathname)}`;throw new Error('Authentication required.')}if(!r.ok)throw new Error(d.error||'Request failed.');return d;}
function matches(x){const q=document.getElementById('search').value.trim().toLowerCase();if(!q)return true;return [x.reference,x.supervisorName,x.email,x.studyCentres,x.payrollStatusLabel,x.payrollNote].join(' ').toLowerCase().includes(q)}
function render(){const list=rows.filter(matches);document.getElementById('count').textContent=list.length;document.getElementById('empty').hidden=!!list.length;document.getElementById('rows').innerHTML=list.map((x,i)=>`<tr><td>${i+1}</td><td><strong>${esc(x.reference)}</strong><br><small>${esc(x.studentStream)}</small></td><td>${esc(x.supervisorName)}<br><small>${esc(x.email)}</small></td><td>${esc(x.studyCentres)}</td><td>${esc(fmt(x.approvedAt))}<br><small>${esc(x.approvedBy)}</small></td><td>${esc(x.claimedGroupCount??x.claimedGroupsRaw)}</td><td>${esc(x.scoreSheetGroupCount)}</td><td>${esc(x.completedProjectWorkCount)}</td><td class="${x.groupValidation?.valid?'check-ok':'check-bad'}">${x.groupValidation?.valid?'MATCH':'MISMATCH'}</td><td>${x.claimFormPresent?`<button class="btn" onclick="openClaim('${esc(x.id)}','${esc(x.reference)}')">Preview</button>`:'<span class="check-bad">Missing</span>'}</td><td><span class="status ${esc(x.payrollStatus)}">${esc(x.payrollStatusLabel)}</span></td><td class="note">${esc(x.payrollNote||'')}</td><td>${(roleRank[identity.role]||0)>=2?`<div class="actions"><button class="btn good" onclick="setStatus('${esc(x.id)}','verified')">Verified</button><button class="btn primary" onclick="setStatus('${esc(x.id)}','approved-for-payment')">Approve for Payment</button><button class="btn good" onclick="setStatus('${esc(x.id)}','paid')">Paid</button><button class="btn warn" onclick="setStatus('${esc(x.id)}','queried')">Query / Hold</button><button class="btn" onclick="setStatus('${esc(x.id)}','pending')">Reset</button></div>`:'Read only'}</td></tr>`).join('');}
window.openClaim=(id,ref)=>{document.getElementById('claimTitle').textContent=`Claim Form · ${ref}`;document.getElementById('claimFrame').src=`/api/admin/${encodeURIComponent(department)}/submissions/${encodeURIComponent(id)}/claim-preview`;document.getElementById('claimDialog').showModal()};
window.setStatus=async(id,status)=>{let note='';if(status==='queried'||status==='paid'||status==='approved-for-payment'){const entered=prompt(status==='queried'?'Enter query/hold reason:':status==='paid'?'Enter payment reference or note (optional):':'Enter approval note (optional):','');if(entered===null)return;note=entered.trim()}try{await get(`/api/payroll/${encodeURIComponent(department)}/claims/${encodeURIComponent(id)}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,note})});await load()}catch(e){alert(e.message)}};
async function load(){const [info,data]=await Promise.all([get(`/api/admin/${encodeURIComponent(department)}/info`),get(`/api/payroll/${encodeURIComponent(department)}/claims`)]);identity=info.admin||{};rows=data;document.getElementById('departmentName').textContent=info.departmentName;document.getElementById('adminLink').href=`/admin/${encodeURIComponent(department)}`;document.getElementById('auditorLink').href=`/auditor/${encodeURIComponent(department)}`;document.getElementById('approvedRegister').href=`/api/payroll/${encodeURIComponent(department)}/approved-register.xlsx`;document.getElementById('payrollRegister').href=`/api/payroll/${encodeURIComponent(department)}/register.xlsx`;render()}
document.getElementById('search').oninput=render;document.getElementById('closeClaim').onclick=()=>{document.getElementById('claimFrame').src='about:blank';document.getElementById('claimDialog').close()};document.getElementById('logoutBtn').onclick=async()=>{await fetch('/api/admin-logout',{method:'POST'}).catch(()=>{});location.href='/'};load().catch(e=>{console.error(e);alert(e.message)});
