let submissions=[],active='all';const tbody=document.getElementById('submissionRows'),search=document.getElementById('search'),empty=document.getElementById('emptyState'),dialog=document.getElementById('detailDialog');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const fmt=v=>{try{return new Date(v).toLocaleString()}catch{return v||''}};const label=t=>t==='project-work'?'Project Work':t==='dissertation'?'Dissertation':'Assessor';
async function load(){const [a,b]=await Promise.all([fetch('/api/admin/submissions'),fetch('/api/admin/summary')]);submissions=await a.json();const s=await b.json();for(const k of ['total','project','dissertation','assessor','scoreRows'])document.getElementById(k).textContent=s[k]??0;render();}
function filtered(){const q=search.value.trim().toLowerCase();return submissions.filter(s=>(active==='all'||s.portalType===active)&&(!q||[s.reference,s.name,s.secondaryName,s.email,s.phone,s.programme,s.studyCentre].join(' ').toLowerCase().includes(q)));}
function rowActions(s){let extras='';if(s.portalType==='project-work')extras=`<a class="btn small" href="/api/admin/submissions/${s.id}/files/scoresFile">Scores</a><a class="btn small" href="/api/admin/submissions/${s.id}/scores.xlsx">Clean Scores</a>`;return `<div class="files">${extras}<button class="btn small" onclick="showDetail('${s.id}')">View Record</button></div>`;}
function render(){const rows=filtered();tbody.innerHTML=rows.map(s=>`<tr><td><span class="ref">${esc(s.reference)}</span></td><td>${esc(fmt(s.submittedAt))}</td><td><span class="tag">${label(s.portalType)}</span></td><td>${esc(s.name)}<br><small>${esc(s.email)}</small></td><td>${esc(s.studyCentre||s.secondaryName||'')}</td><td>${esc(s.programme|| (s.portalType==='project-work'?`${s.scoreRows} score rows`:''))}</td><td>${rowActions(s)}</td></tr>`).join('');empty.classList.toggle('hidden',rows.length>0);}
search.addEventListener('input',render);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;render();});
function item(labelTxt,value){return value?`<div class="detail-item"><span>${esc(labelTxt)}</span><strong>${esc(value)}</strong></div>`:''}
function fileLink(s,kind,labelTxt,item){return item?`<a href="/api/admin/submissions/${s.id}/files/${kind}">${esc(labelTxt)} · ${esc(item.originalName||'Download')}</a>`:''}
window.showDetail=async id=>{const r=await fetch(`/api/admin/submissions/${id}`),s=await r.json();document.getElementById('detailReference').textContent=s.reference||'';let details='',files='';
if((s.portalType||'project-work')==='project-work'){details=item('Supervisor / Examiner',s.fullName)+item('Phone',s.phone)+item('Email',s.email)+item('Study Centre',s.studyCentre)+item('Groups / Candidates',s.groupCount)+item('Score rows extracted',s.scoreSheet?.rowCount);files=fileLink(s,'claimForm','Claim form',s.files?.claimForm)+fileLink(s,'reportFile','Report',s.files?.reportFile)+fileLink(s,'scoresFile','Original score sheet',s.files?.scoresFile)+(s.files?.completedWork||[]).map((f,i)=>`<a href="/api/admin/submissions/${s.id}/files/completedWork/${i}">Project work · ${esc(f.originalName)}</a>`).join('')+`<a href="/api/admin/submissions/${s.id}/scores.xlsx"><strong>Download this submission as a clean score sheet</strong></a>`;}
else if(s.portalType==='dissertation'){details=item('Student Name',s.studentName)+item('Index Number',s.indexNumber)+item('Phone',s.phone)+item('Email',s.email)+item('Supervisor',s.supervisorName)+item('Programme',s.programme)+item('Dissertation Topic',s.dissertationTopic);files=fileLink(s,'dissertationFile','Dissertation',s.files?.dissertationFile);}
else{details=item('Assessor',s.assessorName)+item('Phone',s.phone)+item('Email',s.email)+item('Student Name',s.studentName)+item('Index Number',s.indexNumber)+item('Programme',s.programme);files=fileLink(s,'reportFile','Assessment report',s.files?.reportFile)+fileLink(s,'dissertationFile','Dissertation',s.files?.dissertationFile)+fileLink(s,'claimForm','Claim form',s.files?.claimForm);}
document.getElementById('detailBody').innerHTML=`<div class="detail"><div class="detail-grid">${item('Portal',label(s.portalType||'project-work'))}${item('Submitted',fmt(s.submittedAt))}${details}</div><h3>Submitted files</h3><div class="file-list">${files||'<span>No file available.</span>'}</div></div>`;dialog.showModal();};
document.getElementById('closeDialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});load().catch(e=>{console.error(e);tbody.innerHTML='<tr><td colspan="7">Could not load submissions.</td></tr>';});
