const department=location.pathname.split('/').filter(Boolean)[1]||'';
const apiBase=`/api/admin/${encodeURIComponent(department)}`;
let submissions=[],dissertationAssignments=[],adminIdentity={role:'viewer',sections:['project-work','field-experience','dissertation','assessor'],master:false,name:''};
const roleRank={viewer:1,officer:2,administrator:3},sectionMap={project:'project-work',dissertation:'dissertation',assessor:'assessor'};
const can=(section,role='viewer')=>(adminIdentity.sections||[]).includes(section)&&(roleRank[adminIdentity.role]||0)>=(roleRank[role]||1);
const selectedProject=new Set(),selectedNonResidentialProject=new Set(),selectedFieldExperience=new Set(),selectedDissertations=new Set(),selectedAssessors=new Set(),selectedAssignments=new Set();
const dissertationSort=document.getElementById('dissertationSort'),search=document.getElementById('search'),dialog=document.getElementById('detailDialog'),assignmentDialog=document.getElementById('assignmentDialog'),assignmentForm=document.getElementById('assignmentForm');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=v=>{if(!v)return '';try{return new Date(v).toLocaleString()}catch{return v||''}};
const byType=t=>submissions.filter(s=>s.portalType===t);
const isNonResidentialProject=s=>String(s?.projectStream||'').toLowerCase()==='non-residential'||String(s?.studyCentre||'').trim().toLowerCase()==='non-residential';
const distanceProjectRows=()=>byType('project-work').filter(s=>!isNonResidentialProject(s));
const nonResidentialProjectRows=()=>byType('project-work').filter(isNonResidentialProject);
const matchesSearch=s=>{const q=(search?.value||'').trim().toLowerCase();if(!q)return true;return [s.reference,s.name,s.secondaryName,s.email,s.phone,s.programme,s.studyCentre,s.studentName,s.indexNumber,s.dissertationTopic,s.previousDissertationTopic,s.supervisorName,s.assessorName,s.submissionType,s.reportType,s.assignmentReference,s.returnReason].join(' ').toLowerCase().includes(q)};
const pruneSet=(set,valid)=>{for(const id of [...set])if(!valid.has(id))set.delete(id)};

async function load(){
  const [infoRes,subRes,sumRes,assignRes]=await Promise.all([fetch(`${apiBase}/info`),fetch(`${apiBase}/submissions`),fetch(`${apiBase}/summary`),fetch(`${apiBase}/dissertation-assignments`)]);
  if([infoRes,subRes,sumRes,assignRes].some(r=>r.status===401)){location.href=`/admin-login.html?department=${encodeURIComponent(department)}`;return;}
  if(!infoRes.ok||!subRes.ok||!sumRes.ok||!assignRes.ok)throw new Error('Could not load this department portal.');
  const info=await infoRes.json();adminIdentity=info.admin||adminIdentity;submissions=await subRes.json();dissertationAssignments=await assignRes.json();const s=await sumRes.json();
  pruneSet(selectedProject,new Set(distanceProjectRows().map(x=>x.id)));pruneSet(selectedNonResidentialProject,new Set(nonResidentialProjectRows().map(x=>x.id)));pruneSet(selectedFieldExperience,new Set(byType('field-experience').map(x=>x.id)));pruneSet(selectedDissertations,new Set(byType('dissertation').map(x=>x.id)));pruneSet(selectedAssessors,new Set(byType('assessor').map(x=>x.id)));pruneSet(selectedAssignments,new Set(dissertationAssignments.map(x=>x.id)));
  document.getElementById('departmentName').textContent=info.departmentName;document.getElementById('adminIdentity').textContent=`${adminIdentity.name||adminIdentity.username||'Administrator'} · ${adminIdentity.role}`;document.title=`${info.departmentName} · Submission Administration`;
  applyPermissions();
  for(const k of ['total','project','distanceProject','nonResidentialProject','fieldExperience','dissertation','assessor','scoreRows','nonResidentialScoreRows','fieldScoreRows']){const el=document.getElementById(k);if(el)el.textContent=s[k]??0;}
  document.getElementById('projectTabCount').textContent=(s.project??0)+(s.fieldExperience??0);document.getElementById('dissertationTabCount').textContent=s.dissertation??0;document.getElementById('assessorTabCount').textContent=s.assessor??0;
  document.getElementById('projectScoresLink').href=`${apiBase}/export/project-scores.xlsx`;document.getElementById('projectProgrammeCentreLink').href=`${apiBase}/export/project-programme-centre.zip`;document.getElementById('projectMasterLink').href=`${apiBase}/export/project-master.xlsx`;document.getElementById('projectRegisterLink').href=`${apiBase}/export/project-register.xlsx`;document.getElementById('nonResidentialProjectScoresLink').href=`${apiBase}/export/non-residential-project-scores.xlsx`;document.getElementById('nonResidentialProjectProgrammeCentreLink').href=`${apiBase}/export/non-residential-project-programme-centre.zip`;document.getElementById('nonResidentialProjectMasterLink').href=`${apiBase}/export/non-residential-project-master.xlsx`;document.getElementById('nonResidentialProjectRegisterLink').href=`${apiBase}/export/non-residential-project-register.xlsx`;document.getElementById('fieldScoresLink').href=`${apiBase}/export/field-experience-scores.xlsx`;document.getElementById('fieldMasterLink').href=`${apiBase}/export/field-experience-master.xlsx`;document.getElementById('fieldRegisterLink').href=`${apiBase}/export/field-experience-register.xlsx`;
  document.getElementById('freshDissertationRegisterLink').href=`${apiBase}/export/fresh-dissertation-register.xlsx`;document.getElementById('revisedDissertationRegisterLink').href=`${apiBase}/export/revised-dissertation-register.xlsx`;
  render();
}
function applyPermissions(){
  const projectAllowed=can('project-work')||can('field-experience');document.querySelectorAll('.admin-tab').forEach(b=>{const section=sectionMap[b.dataset.tab]||'';b.hidden=b.dataset.tab==='project'?!projectAllowed:!can(section)});document.querySelectorAll('.admin-tab-panel').forEach(p=>{const section=sectionMap[p.dataset.tabPanel]||'';p.hidden=p.dataset.tabPanel==='project'?!projectAllowed:!can(section)});
  const hide=(id,v)=>{const e=document.getElementById(id);if(e)e.hidden=v};hide('projectWorkSubsection',!can('project-work'));hide('fieldExperienceSubsection',!can('field-experience'));
  ['emailSelectedFresh','emailSelectedRevised'].forEach(id=>hide(id,!can('dissertation','officer')));hide('deleteSelectedDissertations',!can('dissertation','administrator'));hide('deleteSelectedAssignments',!can('dissertation','administrator'));hide('selectAllAssignments',!can('dissertation','administrator'));hide('clearAssignments',!can('dissertation','administrator'));
  hide('deleteSelectedProject',!can('project-work','administrator'));hide('selectAllProject',!can('project-work','viewer'));hide('clearProject',!can('project-work','viewer'));hide('downloadSelectedProjectClaims',!can('project-work','viewer'));hide('emailSelectedProjectClaims',!can('project-work','officer'));hide('deleteSelectedNonResidentialProject',!can('project-work','administrator'));hide('selectAllNonResidentialProject',!can('project-work','viewer'));hide('clearNonResidentialProject',!can('project-work','viewer'));hide('downloadSelectedNonResidentialProjectClaims',!can('project-work','viewer'));hide('emailSelectedNonResidentialProjectClaims',!can('project-work','officer'));hide('deleteSelectedField',!can('field-experience','administrator'));hide('selectAllField',!can('field-experience','administrator'));hide('clearField',!can('field-experience','administrator'));hide('deleteSelectedAssessors',!can('assessor','administrator'));hide('selectAllAssessors',!can('assessor','administrator'));hide('clearAssessors',!can('assessor','administrator'));
  const first=[...document.querySelectorAll('.admin-tab')].find(b=>!b.hidden);if(first&&!document.querySelector('.admin-tab.active:not([hidden])'))activateAdminTab(first.dataset.tab);
}
function render(){renderProject();renderFieldExperience();renderDissertations();renderAssignments();renderAssessors();updateSelectionButtons()}

function reviewBadge(s,prefix='project'){const status=s[`${prefix}ReviewStatus`]||'pending',label=s[`${prefix}ReviewLabel`]||status;return `<span class="project-review-badge review-${esc(status)}">${esc(label)}</span>`}
function warningSummary(s,prefix='project'){const list=Array.isArray(s[`${prefix}Warnings`])?s[`${prefix}Warnings`]:[];return list.length?`<span class="warning-count" title="${esc(list.map(w=>w.message).join(' | '))}">⚠ ${list.length} warning${list.length===1?'':'s'}</span>`:'<span class="warning-clear">No flags</span>'}
function projectRowHtml(s,i,selectionSet,checkClass,label){return `<tr class="project-review-row review-row-${esc(s.projectReviewStatus||'pending')}"><td>${i+1}</td><td><span class="ref">${esc(s.reference)}</span></td><td>${esc(s.name)}<br><small>${esc(s.email)}</small></td><td>${esc(s.studyCentre)}</td><td>${esc(s.scoreRows)}</td><td>${esc(fmt(s.submittedAt))}</td><td>${reviewBadge(s)}</td><td>${warningSummary(s)}</td><td><input class="row-check ${checkClass}" type="checkbox" data-id="${esc(s.id)}" ${selectionSet.has(s.id)?'checked':''}></td><td><div class="files"><a class="btn small" href="${apiBase}/submissions/${s.id}/files/scoresFile">Original Scores</a><a class="btn small" href="${apiBase}/submissions/${s.id}/scores.xlsx">Clean Scores</a><button class="btn small" onclick="showDetail('${s.id}')">${can('project-work','administrator')?'Review':'View'}</button>${can('project-work','administrator')?`<button class="btn small danger" onclick="deleteOneSubmission('${s.id}','${label}')">Delete</button>`:''}</div></td></tr>`}
function renderProject(){const distance=distanceProjectRows().filter(matchesSearch),distanceBody=document.getElementById('projectRows');distanceBody.innerHTML=distance.map((s,i)=>projectRowHtml(s,i,selectedProject,'project-check','Distance project work')).join('');document.getElementById('projectEmpty').classList.toggle('hidden',!!distance.length);distanceBody.querySelectorAll('.project-check').forEach(c=>c.onchange=()=>{c.checked?selectedProject.add(c.dataset.id):selectedProject.delete(c.dataset.id);updateSelectionButtons()});const regular=nonResidentialProjectRows().filter(matchesSearch),regularBody=document.getElementById('nonResidentialProjectRows');regularBody.innerHTML=regular.map((s,i)=>projectRowHtml(s,i,selectedNonResidentialProject,'nonres-project-check','Non-Residential project work')).join('');document.getElementById('nonResidentialProjectEmpty').classList.toggle('hidden',!!regular.length);regularBody.querySelectorAll('.nonres-project-check').forEach(c=>c.onchange=()=>{c.checked?selectedNonResidentialProject.add(c.dataset.id):selectedNonResidentialProject.delete(c.dataset.id);updateSelectionButtons()})}
function renderFieldExperience(){const rows=byType('field-experience').filter(matchesSearch),tbody=document.getElementById('fieldRows');tbody.innerHTML=rows.map((s,i)=>`<tr class="project-review-row review-row-${esc(s.fieldReviewStatus||'pending')}"><td>${i+1}</td><td><span class="ref">${esc(s.reference)}</span></td><td>${esc(s.name)}<br><small>${esc(s.email)}</small></td><td>${esc(s.studyCentre)}</td><td>${esc(s.scoreRows)}</td><td>${esc(fmt(s.submittedAt))}</td><td>${reviewBadge(s,'field')}</td><td>${warningSummary(s,'field')}</td><td><input class="row-check field-check" type="checkbox" data-id="${esc(s.id)}" ${selectedFieldExperience.has(s.id)?'checked':''}></td><td><div class="files"><a class="btn small" href="${apiBase}/submissions/${s.id}/files/scoresFile">Original Scores</a><a class="btn small" href="${apiBase}/submissions/${s.id}/scores.xlsx">Clean Scores</a><button class="btn small" onclick="showDetail('${s.id}')">${can('field-experience','administrator')?'Review':'View'}</button>${can('field-experience','administrator')?`<button class="btn small danger" onclick="deleteOneSubmission('${s.id}','Field Experience score submission')">Delete</button>`:''}</div></td></tr>`).join('');document.getElementById('fieldEmpty').classList.toggle('hidden',!!rows.length);tbody.querySelectorAll('.field-check').forEach(c=>c.onchange=()=>{c.checked?selectedFieldExperience.add(c.dataset.id):selectedFieldExperience.delete(c.dataset.id);updateSelectionButtons()})}

function dissertationState(s){const n=Number(s.assignmentCount||0),type=s.submissionType||'fresh';if(type==='final')return 'neutral';if(type==='revised')return n===0?'red':'green';return n===0?'red':n===1?'amber':'green'}
function assignmentCounter(s){if((s.submissionType||'fresh')==='final')return '<span class="assignment-counter counter-neutral">Final</span>';const n=Number(s.assignmentCount||0),limit=Number(s.assignmentLimit||((s.submissionType==='revised')?2:3)),names=(s.assignedAssessors||[]).map(a=>a.name||a.email).filter(Boolean),role=s.submissionType==='revised'?'vetter':'assessor',state=dissertationState(s);return `<span class="assignment-counter counter-${state}" title="${esc(names.join(', ')||`No ${role} assigned`)}">${n} / ${limit}</span>${names.length?`<small class="assessor-list">${esc(names.join(', '))}</small>`:''}`}
function processBadge(s){if(s.processingStatus==='returned')return `<span class="processing-badge returned" title="${esc(s.returnReason||'Returned to student')}">Returned to Student</span>`;return '<span class="processing-badge received">Received</span>'}
function dissertationSortRows(rows){const mode=dissertationSort?.value||'newest',c=rows.slice();if(mode==='assessors-asc')c.sort((a,b)=>Number(a.assignmentCount||0)-Number(b.assignmentCount||0)||new Date(b.submittedAt||0)-new Date(a.submittedAt||0));else if(mode==='assessors-desc')c.sort((a,b)=>Number(b.assignmentCount||0)-Number(a.assignmentCount||0)||new Date(b.submittedAt||0)-new Date(a.submittedAt||0));else c.sort((a,b)=>new Date(b.submittedAt||0)-new Date(a.submittedAt||0));return c}
function dissertationRow(s,i){const type=s.submissionType||'fresh',isRev=type==='revised',isFinal=type==='final',state=dissertationState(s),changed=s.previousDissertationTopic&&s.previousDissertationTopic.trim()!==s.dissertationTopic.trim();return `<tr class="dissertation-state-${state} ${s.processingStatus==='returned'?'dissertation-returned':''}"><td>${i+1}</td><td>${esc(s.studentName||s.name)}</td><td><span class="ref">${esc(s.indexNumber)}</span></td><td class="title-cell">${esc(s.dissertationTopic)}${s.titleValidated?'<br><small class="validated-text">✓ Title validated</small>':''}${isRev&&changed?'<br><small class="title-change-note">Title changed from previous stage</small>':''}</td><td>${esc(s.programme)}</td><td>${esc(s.supervisorName||s.secondaryName)}</td>${isFinal?`<td>${s.reviewerResponseCount||0} response file(s)<br>${s.turnitinReportPresent?'✓ Turnitin':'Turnitin missing'}</td>`:`<td>${assignmentCounter(s)}</td>`}<td>${processBadge(s)}</td><td><input class="row-check dissertation-check" type="checkbox" data-id="${esc(s.id)}" ${selectedDissertations.has(s.id)?'checked':''}></td><td><div class="files"><a class="btn small primary" href="${apiBase}/submissions/${s.id}/files/dissertationFile">${isFinal?'Final Dissertation':isRev?'Revised Dissertation':'Dissertation'}</a><button class="btn small" onclick="showDetail('${s.id}')">View</button>${can('dissertation','officer')&&s.processingStatus!=='returned'?`<button class="btn small return" onclick="returnDissertation('${s.id}','${esc(type)}')">Return to Student</button>`:''}${can('dissertation','administrator')?`<button class="btn small danger" onclick="deleteOneSubmission('${s.id}','dissertation')">Delete</button>`:''}</div></td></tr>`}
function wireDissertationChecks(body){body.querySelectorAll('.dissertation-check').forEach(c=>c.onchange=()=>{c.checked?selectedDissertations.add(c.dataset.id):selectedDissertations.delete(c.dataset.id);updateSelectionButtons()})}
function renderDissertations(){const all=dissertationSortRows(byType('dissertation').filter(matchesSearch)),fresh=all.filter(s=>(s.submissionType||'fresh')==='fresh'),rev=all.filter(s=>s.submissionType==='revised'),fin=all.filter(s=>s.submissionType==='final');for(const [type,rows,id,empty,count] of [['fresh',fresh,'freshDissertationRows','freshDissertationEmpty','freshDissertationCount'],['revised',rev,'revisedDissertationRows','revisedDissertationEmpty','revisedDissertationCount'],['final',fin,'finalDissertationRows','finalDissertationEmpty','finalDissertationCount']]){const b=document.getElementById(id);b.innerHTML=rows.map(dissertationRow).join('');document.getElementById(empty).classList.toggle('hidden',!!rows.length);document.getElementById(count).textContent=rows.length;wireDissertationChecks(b)}}

function assignmentStatusBadge(a){const m={sent:'Sent',downloaded:'Downloaded','download-expired':'Download expired','in-progress':'In progress',completed:'Completed',revoked:'Revoked','email-failed':'Email failed',pending:'Pending'};return `<span class="status-badge status-${esc(a.status||'pending')}">${esc(m[a.status]||a.status||'Pending')}</span>`}
function assignmentTypeBadge(t){return `<span class="submission-type ${t==='vetting'?'revised':'fresh'}">${t==='vetting'?'Vetting':'Assessment'}</span>`}
function renderAssignments(){const body=document.getElementById('assignmentRows');body.innerHTML=dissertationAssignments.map((a,i)=>{const submitted=Number(a.submittedCount||0),total=Number(a.dissertationCount||0),role=a.assignmentType==='vetting'?'Vetter':'Assessor';return `<tr><td>${i+1}</td><td><span class="ref">${esc(a.reference)}</span></td><td>${assignmentTypeBadge(a.assignmentType||'assessment')}</td><td>${esc((a.studentNames||[]).join(', ')||'—')}</td><td><small>${role}</small><br>${esc(a.assessorName)}</td><td>${esc(a.assessorEmail)}</td><td><strong>${submitted} / ${total}</strong><br><small>${total-submitted} pending${a.earlyBirdCount?` · ${a.earlyBirdCount} Early Bird`:''}</small></td><td>${a.sentAt?esc(fmt(a.sentAt)):'Not sent'}</td><td>${esc(fmt(a.earlyBirdDueAt))}</td><td>${esc(fmt(a.assessmentDueAt))}</td><td>${esc(fmt(a.expiresAt))}</td><td>${assignmentStatusBadge(a)}</td><td>${a.downloadedAt?`${esc(fmt(a.downloadedAt))}<br><small>${esc(a.downloadCount)} downloads</small>`:'Not downloaded'}</td><td>${can('dissertation','administrator')?`<input class="row-check assignment-check" type="checkbox" data-id="${esc(a.id)}" ${selectedAssignments.has(a.id)?'checked':''}>`:''}</td><td><div class="files">${can('dissertation','officer')?`<button class="btn small" onclick="resendAssignment('${a.id}')">Resend Link</button>${a.status!=='revoked'?`<button class="btn small danger" onclick="revokeAssignment('${a.id}')">Revoke</button>`:''}`:''}</div>${a.lastEmailError?`<small class="error-text">${esc(a.lastEmailError)}</small>`:''}</td></tr>`}).join('');document.getElementById('assignmentEmpty').classList.toggle('hidden',!!dissertationAssignments.length);body.querySelectorAll('.assignment-check').forEach(c=>c.onchange=()=>{c.checked?selectedAssignments.add(c.dataset.id):selectedAssignments.delete(c.dataset.id);updateSelectionButtons()})}

function feedbackSummary(s){const states=s.feedbackStates||[];if(!states.length)return '<small>No work records</small>';return `<div class="feedback-summary">${states.map((f,i)=>`<span class="feedback-chip feedback-${esc(f.state)}" title="Work ${i+1}">W${i+1}</span>`).join('')}</div>`}
function assessorRow(s,i){const workTag=s.assignmentWorkNo?`<br><small>Work ${esc(s.assignmentWorkNo)} of ${esc(s.assignmentTotalWorks||'')} ${s.earlyBirdQualified?'· Early Bird ✓':''}</small>`:'';return `<tr><td>${i+1}</td><td><span class="ref">${esc(s.reference)}</span>${s.assignmentReference?`<br><small>${esc(s.assignmentReference)}</small>`:''}${workTag}</td><td>${esc(s.assessorName||s.name)}</td><td>${esc(s.workCount||1)}</td><td>${esc(s.studentName||s.secondaryName)}</td><td>${esc(s.indexNumber)}</td><td>${esc(s.programme)}</td><td>${feedbackSummary(s)}</td><td>${esc(fmt(s.submittedAt))}</td><td><input class="row-check assessor-check" type="checkbox" data-id="${esc(s.id)}" ${selectedAssessors.has(s.id)?'checked':''}></td><td><div class="files"><button class="btn small primary" onclick="showDetail('${s.id}')">View / Forward / Download</button>${can('assessor','administrator')?`<button class="btn small danger" onclick="deleteOneSubmission('${s.id}','report submission')">Delete</button>`:''}</div></td></tr>`}
function renderAssessors(){const all=byType('assessor').filter(matchesSearch),assessment=all.filter(s=>(s.reportType||'assessment')==='assessment'),vetting=all.filter(s=>s.reportType==='vetting');for(const [rows,id,empty,count] of [[assessment,'assessmentRows','assessmentEmpty','assessmentReportCount'],[vetting,'vettingRows','vettingEmpty','vettingReportCount']]){const b=document.getElementById(id);b.innerHTML=rows.map(assessorRow).join('');document.getElementById(empty).classList.toggle('hidden',!!rows.length);document.getElementById(count).textContent=rows.length;b.querySelectorAll('.assessor-check').forEach(c=>c.onchange=()=>{c.checked?selectedAssessors.add(c.dataset.id):selectedAssessors.delete(c.dataset.id);updateSelectionButtons()})}}

function updateSelectionButtons(){const set=(id,disabled,textId,count)=>{const e=document.getElementById(id);if(e)e.disabled=disabled;const t=textId&&document.getElementById(textId);if(t)t.textContent=`(${count})`};set('deleteSelectedProject',!selectedProject.size||!can('project-work','administrator'),'projectSelectedCount',selectedProject.size);set('downloadSelectedProjectClaims',!selectedProject.size||!can('project-work','viewer'),'projectClaimSelectedCount',selectedProject.size);set('emailSelectedProjectClaims',!selectedProject.size||!can('project-work','officer'),null,selectedProject.size);set('deleteSelectedNonResidentialProject',!selectedNonResidentialProject.size||!can('project-work','administrator'),'nonResidentialProjectSelectedCount',selectedNonResidentialProject.size);set('downloadSelectedNonResidentialProjectClaims',!selectedNonResidentialProject.size||!can('project-work','viewer'),'nonResidentialProjectClaimSelectedCount',selectedNonResidentialProject.size);set('emailSelectedNonResidentialProjectClaims',!selectedNonResidentialProject.size||!can('project-work','officer'),null,selectedNonResidentialProject.size);set('deleteSelectedField',!selectedFieldExperience.size||!can('field-experience','administrator'),'fieldSelectedCount',selectedFieldExperience.size);set('deleteSelectedAssessors',!selectedAssessors.size||!can('assessor','administrator'),'assessorSelectedCount',selectedAssessors.size);set('deleteSelectedAssignments',!selectedAssignments.size||!can('dissertation','administrator'),'assignmentSelectedCount',selectedAssignments.size);set('downloadSelectedDissertations',!selectedDissertations.size,'selectedCount',selectedDissertations.size);document.getElementById('deleteSelectedDissertations').disabled=!selectedDissertations.size||!can('dissertation','administrator');const fresh=[...selectedDissertations].map(id=>submissions.find(s=>s.id===id)).filter(s=>(s?.submissionType||'fresh')==='fresh'),rev=[...selectedDissertations].map(id=>submissions.find(s=>s.id===id)).filter(s=>s?.submissionType==='revised');document.getElementById('emailSelectedFresh').disabled=!fresh.length||fresh.some(s=>s.processingStatus==='returned'||Number(s.assignmentCount)>=3)||!can('dissertation','officer');document.getElementById('emailSelectedRevised').disabled=!rev.length||rev.some(s=>s.processingStatus==='returned'||Number(s.assignmentCount)>=2)||!can('dissertation','officer')}

function setStageSelection(type){selectedDissertations.clear();byType('dissertation').filter(s=>s.submissionType===type||((s.submissionType||'fresh')==='fresh'&&type==='fresh')).filter(matchesSearch).forEach(s=>selectedDissertations.add(s.id));renderDissertations();updateSelectionButtons()}
document.getElementById('selectAllFreshDissertations').onclick=()=>setStageSelection('fresh');document.getElementById('selectAllRevisedDissertations').onclick=()=>setStageSelection('revised');document.getElementById('selectAllFinalDissertations').onclick=()=>setStageSelection('final');document.getElementById('clearDissertations').onclick=()=>{selectedDissertations.clear();renderDissertations();updateSelectionButtons()};
document.getElementById('selectAllProject').onclick=()=>{distanceProjectRows().filter(matchesSearch).forEach(s=>selectedProject.add(s.id));renderProject();updateSelectionButtons()};document.getElementById('clearProject').onclick=()=>{selectedProject.clear();renderProject();updateSelectionButtons()};document.getElementById('selectAllNonResidentialProject').onclick=()=>{nonResidentialProjectRows().filter(matchesSearch).forEach(s=>selectedNonResidentialProject.add(s.id));renderProject();updateSelectionButtons()};document.getElementById('clearNonResidentialProject').onclick=()=>{selectedNonResidentialProject.clear();renderProject();updateSelectionButtons()};document.getElementById('selectAllField').onclick=()=>{byType('field-experience').filter(matchesSearch).forEach(s=>selectedFieldExperience.add(s.id));renderFieldExperience();updateSelectionButtons()};document.getElementById('clearField').onclick=()=>{selectedFieldExperience.clear();renderFieldExperience();updateSelectionButtons()};document.getElementById('selectAllAssessors').onclick=()=>{byType('assessor').filter(matchesSearch).forEach(s=>selectedAssessors.add(s.id));renderAssessors();updateSelectionButtons()};document.getElementById('clearAssessors').onclick=()=>{selectedAssessors.clear();renderAssessors();updateSelectionButtons()};document.getElementById('selectAllAssignments').onclick=()=>{dissertationAssignments.forEach(a=>selectedAssignments.add(a.id));renderAssignments();updateSelectionButtons()};document.getElementById('clearAssignments').onclick=()=>{selectedAssignments.clear();renderAssignments();updateSelectionButtons()};

async function deleteSelected(set,label){const ids=[...set];if(!ids.length||!confirm(`Delete ${ids.length} selected ${label}? This cannot be undone.`))return;const r=await fetch(`${apiBase}/submissions/delete-selected`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Delete failed.');set.clear();await load()}
document.getElementById('deleteSelectedProject').onclick=()=>deleteSelected(selectedProject,'Distance project-work submission(s)').catch(e=>alert(e.message));document.getElementById('deleteSelectedNonResidentialProject').onclick=()=>deleteSelected(selectedNonResidentialProject,'Non-Residential project-work submission(s)').catch(e=>alert(e.message));document.getElementById('deleteSelectedField').onclick=()=>deleteSelected(selectedFieldExperience,'Field Experience submission(s)').catch(e=>alert(e.message));document.getElementById('deleteSelectedDissertations').onclick=()=>deleteSelected(selectedDissertations,'dissertation submission(s)').catch(e=>alert(e.message));document.getElementById('deleteSelectedAssessors').onclick=()=>deleteSelected(selectedAssessors,'report submission(s)').catch(e=>alert(e.message));
window.deleteOneSubmission=async(id,label)=>{if(!confirm(`Delete this ${label}? This cannot be undone.`))return;const r=await fetch(`${apiBase}/submissions/${encodeURIComponent(id)}`,{method:'DELETE'}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Delete failed.');if(dialog.open)dialog.close();await load()};
document.getElementById('deleteSelectedAssignments').onclick=async()=>{if(!selectedAssignments.size||!confirm('Delete selected assignment records? Their secure links will stop working.'))return;const r=await fetch(`${apiBase}/dissertation-assignments/delete-selected`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[...selectedAssignments]})}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Could not delete assignments.');selectedAssignments.clear();await load()};

document.getElementById('downloadSelectedDissertations').onclick=async()=>{if(!selectedDissertations.size)return;const res=await fetch(`${apiBase}/dissertations/download-selected`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[...selectedDissertations]})});if(!res.ok){const d=await res.json().catch(()=>({}));return alert(d.error||'Could not create ZIP.')}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${department}-selected-dissertations.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
async function downloadProjectClaims(set,stream){if(!set.size)return;const res=await fetch(`${apiBase}/project-claims/download-selected`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[...set],stream})});if(!res.ok){const d=await res.json().catch(()=>({}));return alert(d.error||'Could not create claim-form ZIP.')}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${department}-${stream}-selected-claim-forms.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function emailProjectClaims(set,stream){if(!set.size)return;const recipient=prompt('Department email address to receive the selected claim forms ZIP:','');if(recipient===null)return;if(!recipient.trim())return alert('Enter the department email address.');if(!confirm(`Email ${set.size} selected claim-form submission${set.size===1?'':'s'} to ${recipient.trim()} as one ZIP file?`))return;const res=await fetch(`${apiBase}/project-claims/email-selected`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[...set],stream,recipientEmail:recipient.trim()})}),d=await res.json().catch(()=>({}));if(!res.ok)return alert(d.error||'Could not email the claim forms.');alert(`${d.count} claim form${d.count===1?'':'s'} emailed to ${d.recipient}.`)}
document.getElementById('downloadSelectedProjectClaims').onclick=()=>downloadProjectClaims(selectedProject,'distance');document.getElementById('emailSelectedProjectClaims').onclick=()=>emailProjectClaims(selectedProject,'distance');document.getElementById('downloadSelectedNonResidentialProjectClaims').onclick=()=>downloadProjectClaims(selectedNonResidentialProject,'non-residential');document.getElementById('emailSelectedNonResidentialProjectClaims').onclick=()=>emailProjectClaims(selectedNonResidentialProject,'non-residential');

function openAssignmentFor(type){const rows=[...selectedDissertations].map(id=>submissions.find(s=>s.id===id)).filter(s=>s&&((s.submissionType||'fresh')===type));if(!rows.length)return alert(`Select at least one ${type} dissertation.`);selectedDissertations.clear();rows.forEach(r=>selectedDissertations.add(r.id));const isRev=type==='revised',limit=isRev?2:3,role=isRev?'Vetter':'Assessor';if(rows.some(s=>s.processingStatus==='returned'))return alert('A returned dissertation cannot be assigned. Wait for the student to submit again.');if(rows.some(s=>Number(s.assignmentCount||0)>=limit))return alert(`At least one selected dissertation has reached the maximum of ${limit} ${role.toLowerCase()}${limit===1?'':'s'}.`);document.getElementById('assignmentType').value=isRev?'vetting':'assessment';document.getElementById('assignmentDialogTitle').textContent=`Email Selected to ${role}`;document.getElementById('assignmentSelectionCount').textContent=`${rows.length} ${type} dissertation${rows.length===1?'':'s'} selected`;document.getElementById('assignmentSelectionHelp').textContent=`One secure ${isRev?'vetting':'assessment'} workspace link will contain all selected works. Student details are locked to the assignment.`;for(const [id,text] of [['assignmentRoleTitleLabel',`${role}'s Title`],['assignmentRoleFirstLabel',`${role}'s First Name`],['assignmentRoleLastLabel',`${role}'s Surname / Last Name`],['assignmentRoleEmailLabel',`${role}'s Email`]])document.getElementById(id).textContent=text;document.getElementById('assignmentFormStatus').className='form-status hidden';assignmentDialog.showModal();}
document.getElementById('emailSelectedFresh').onclick=()=>openAssignmentFor('fresh');document.getElementById('emailSelectedRevised').onclick=()=>openAssignmentFor('revised');
function closeAssignmentDialog(){if(assignmentDialog.open)assignmentDialog.close()}document.getElementById('closeAssignmentDialog').onclick=closeAssignmentDialog;document.getElementById('cancelAssignment').onclick=closeAssignmentDialog;
assignmentForm.addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('sendAssignment'),st=document.getElementById('assignmentFormStatus');btn.disabled=true;try{const payload={ids:[...selectedDissertations],assignmentType:document.getElementById('assignmentType').value,assessorTitle:document.getElementById('assignmentAssessorTitle').value.trim(),assessorFirstName:document.getElementById('assignmentAssessorFirstName').value.trim(),assessorLastName:document.getElementById('assignmentAssessorLastName').value.trim(),assessorEmail:document.getElementById('assignmentAssessorEmail').value.trim(),expiryDays:Number(document.getElementById('assignmentExpiryDays').value||14),message:document.getElementById('assignmentMessage').value.trim()};const r=await fetch(`${apiBase}/dissertation-assignments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not send assignment.');selectedDissertations.clear();assignmentForm.reset();document.getElementById('assignmentExpiryDays').value=14;closeAssignmentDialog();await load();alert(`Secure ${d.assignment.assignmentType==='vetting'?'vetting':'assessment'} link sent to ${d.assignment.assessorEmail}.`)}catch(err){st.textContent=err.message;st.className='form-status error'}finally{btn.disabled=false}});
window.revokeAssignment=async id=>{if(!confirm('Revoke this secure link?'))return;const r=await fetch(`${apiBase}/dissertation-assignments/${id}/revoke`,{method:'POST'}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Could not revoke.');await load()};window.resendAssignment=async id=>{const a=dissertationAssignments.find(x=>x.id===id);if(!a)return;const days=prompt('New link validity in days','14');if(days===null)return;const r=await fetch(`${apiBase}/dissertation-assignments/${id}/resend`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiryDays:Number(days)||14})}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Could not resend.');await load()};

window.returnDissertation=async(id,type)=>{const menu='Choose reason:\n1. Fees not paid in full\n2. Plagiarism (Turnitin) report not satisfactory/not valid\n3. Reviewer response not complete/invalid\n4. Other';const choice=prompt(menu,'1');if(choice===null)return;const map={'1':'fees','2':'turnitin','3':'reviewer','4':'other'},reasonCode=map[String(choice).trim()];if(!reasonCode)return alert('Invalid choice.');let otherReason='';if(reasonCode==='other'){otherReason=prompt('Enter the reason for returning the submission:','')||'';if(!otherReason.trim())return alert('Enter a reason.')}if(!confirm('Return this dissertation to the student without further processing? The student will receive the reason by email.'))return;const r=await fetch(`${apiBase}/dissertations/${encodeURIComponent(id)}/return-to-student`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reasonCode,otherReason})}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Could not return dissertation.');if(dialog.open)dialog.close();await load();alert('The dissertation has been returned to the student.')};

function item(label,value){return value!==undefined&&value!==null&&String(value)!==''?`<div><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`:''}
function fileLink(s,kind,label,file,index){if(!file)return '';const suffix=index===undefined?'':`/${index}`;return `<a href="${apiBase}/submissions/${s.id}/files/${kind}${suffix}"><strong>${esc(label)}</strong><small>${esc(file.originalName||'Download')}</small></a>`}
function fileLinks(s,kind,label,arr){return (arr||[]).map((f,i)=>fileLink(s,kind,`${label} ${i+1}`,f,i)).join('')}
function workFileLink(s,i,kind,label,file){return file?`<a href="${apiBase}/submissions/${s.id}/works/${i}/files/${kind}"><strong>${esc(label)}</strong><small>${esc(file.originalName||'Download')}</small></a>`:''}
function feedbackLabel(state){return {'not-forwarded':'Not forwarded',sent:'Forwarded, awaiting download',downloaded:'Downloaded by student',pending:'Sending','email-failed':'Email failed',expired:'Link expired',revoked:'Revoked',unavailable:'No matching student email'}[state]||state}
function assessmentWorksHtml(s,summary){const infos=summary?.feedbackStates||[],reportType=s.reportType||'assessment',label=reportType==='vetting'?'Vetting':'Assessment';return `<div class="privacy-notice"><strong>Student confidentiality:</strong> students must never receive assessor/vetter identity. Upload an anonymised student copy of the report before forwarding. The original report, claim form and score sheet remain internal.</div><div class="assessment-admin-list">${(s.works||[]).map((w,i)=>{const info=infos[i]||{},state=info.state||'not-forwarded',email=info.email||w.studentEmail||'',prepared=Boolean(w.feedback?.studentFiles?.reportFile);return `<section class="assessment-admin-work"><div class="assessment-admin-head"><div><span>Work ${esc(w.workNo||i+1)} · ${label}</span><h4>${esc(w.studentName||'Student')}</h4></div><strong>${esc(w.indexNumber||'')}</strong></div><div class="detail-grid">${item('Programme',w.programme)}${item('Student Email',email||'No matching dissertation email')}</div><div class="file-list work-file-list">${workFileLink(s,i,'reportFile',`${label} report`,w.files?.reportFile)}${workFileLink(s,i,'claimForm','Claim form',w.files?.claimForm)}${workFileLink(s,i,'scoreSheet','Score sheet',w.files?.scoreSheet)}${workFileLink(s,i,'dissertationFile','Reviewed dissertation',w.files?.dissertationFile)}</div><div class="anonymous-forward-box feedback-box-${esc(state)}"><span class="feedback-status"><i></i>${esc(feedbackLabel(state))}</span><p>Upload a report copy with all assessor/vetter names, signatures, email addresses and identifying marks removed. If a reviewed dissertation is to be forwarded, upload an anonymised copy of it too.</p><label>Anonymous Student Report ${prepared?'<small>optional replacement</small>':'*'}<input id="studentReport-${s.id}-${i}" type="file" accept=".pdf,.doc,.docx" ${prepared?'':'required'}></label><label>Anonymous Reviewed Dissertation <small>Optional</small><input id="studentDissertation-${s.id}-${i}" type="file" accept=".pdf,.doc,.docx"></label><div class="files">${can('assessor','officer')&&email?`<button class="btn small email" onclick="forwardFeedback('${s.id}',${i},'${esc(email)}',${prepared})">${prepared?'Resend / Update Anonymous Feedback':'Forward Anonymous Feedback'}</button>`:''}${can('assessor','officer')&&w.feedback&&!['not-forwarded','unavailable','revoked'].includes(state)?`<button class="btn small danger" onclick="revokeFeedback('${s.id}',${i})">Revoke Link</button>`:''}</div></div></section>`}).join('')}</div>`}
window.forwardFeedback=async(id,i,email,prepared)=>{if(!email)return alert('No student email found.');const report=document.getElementById(`studentReport-${id}-${i}`)?.files?.[0],reviewed=document.getElementById(`studentDissertation-${id}-${i}`)?.files?.[0];if(!prepared&&!report)return alert('Upload an anonymised student copy of the report first.');if(!confirm(`Send anonymous feedback to ${email}? The original assessor/vetter report, claim form and score sheet will not be exposed.`))return;const fd=new FormData();if(report)fd.append('studentReportFile',report);if(reviewed)fd.append('studentDissertationFile',reviewed);const r=await fetch(`${apiBase}/submissions/${id}/works/${i}/forward-to-student`,{method:'POST',body:fd}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Could not forward feedback.');alert(`Anonymous feedback link sent to ${d.email}.`);if(dialog.open)dialog.close();await load()};window.revokeFeedback=async(id,i)=>{if(!confirm('Revoke this student feedback link?'))return;const r=await fetch(`${apiBase}/submissions/${id}/works/${i}/revoke-feedback`,{method:'POST'}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Could not revoke.');if(dialog.open)dialog.close();await load()};

function warningPanel(summary,prefix){const list=summary?.[`${prefix}Warnings`]||[];return `<div class="project-warning-panel ${list.length?'has-warnings':'no-warnings'}"><h3>Verification warnings</h3>${list.length?`<ul>${list.map(w=>`<li>${esc(w.message)}</li>`).join('')}</ul>`:'<p>No suspicious-submission flags detected.</p>'}</div>`}
function reviewControls(summary,prefix,section){if(!can(section,'administrator'))return '';const status=summary?.[`${prefix}ReviewStatus`]||'pending',mailStatus=summary?.[`${prefix}ReturnEmailStatus`]||'',mailSentAt=summary?.[`${prefix}ReturnEmailSentAt`]||'',mailError=summary?.[`${prefix}ReturnEmailError`]||'',mailRecipient=summary?.[`${prefix}ReturnEmailRecipient`]||summary?.email||'';const mailInfo=status==='returned'?`<div class="correction-email-status correction-email-${esc(mailStatus||'unknown')}"><strong>Correction email:</strong> ${mailStatus==='sent'?`Sent${mailRecipient?` to ${esc(mailRecipient)}`:''}${mailSentAt?` · ${esc(fmt(mailSentAt))}`:''}`:mailStatus==='failed'?`Failed${mailError?` · ${esc(mailError)}`:''}`:mailStatus==='pending'?'Pending':'Not sent'} ${status==='returned'?`<button class="btn small email" type="button" onclick="resendScoreCorrectionEmail('${summary.id}','${section}')">Resend Correction Email</button>`:''}</div>`:'';return `<div class="project-review-controls"><h3>Verification decision</h3><div class="files"><button class="btn small approve" onclick="setScoreReview('${summary.id}','approved','${section}')" ${status==='approved'?'disabled':''}>Approve for Consolidation</button><button class="btn small danger" onclick="setScoreReview('${summary.id}','rejected','${section}')" ${status==='rejected'?'disabled':''}>Reject</button><button class="btn small return" onclick="setScoreReview('${summary.id}','returned','${section}')" ${status==='returned'?'disabled':''}>Return for Correction</button>${status!=='pending'?`<button class="btn small" onclick="setScoreReview('${summary.id}','pending','${section}')">Reset to Pending</button>`:''}</div>${mailInfo}</div>`}
function scoreReviewTable(record){const rows=Array.isArray(record?.reviewScoreRows)?record.reviewScoreRows:[];if(!rows.length)return `<section class="score-review-section"><div class="score-review-head"><div><h3>Score entries for review</h3><p>No student score rows were detected in this submission.</p></div></div></section>`;const included=rows.filter(r=>r.included!==false).length;return `<section class="score-review-section"><div class="score-review-head"><div><h3>Score entries for review</h3><p>Review the entries below before approval. All rows are checked by default. Uncheck any row that should be excluded from the consolidated and master scores. The original uploaded score sheet is not changed.</p></div><strong id="scoreReviewCount">${included} of ${rows.length} included</strong></div>${can('project-work','administrator')?`<div class="score-review-actions"><button class="btn small" type="button" onclick="setAllScoreRows(true)">Check all</button><button class="btn small" type="button" onclick="setAllScoreRows(false)">Uncheck all</button></div>`:''}<div class="table-scroll score-review-table-wrap"><table class="score-review-table"><thead><tr><th>Include</th><th>S/N</th><th>NAME</th><th>REGISTRATION NO.</th><th>GROUP NO.</th><th>TOTAL SCORE</th></tr></thead><tbody>${rows.map((row,i)=>`<tr class="${row.included===false?'score-row-excluded':''}"><td><input class="score-approval-check" type="checkbox" data-source-index="${Number(row.sourceIndex)}" ${row.included===false?'':'checked'} ${can('project-work','administrator')?'':'disabled'} aria-label="Include ${esc(row.name||`row ${i+1}`)} in approval"></td><td>${esc(row.originalSn||i+1)}</td><td>${esc(row.name)}</td><td>${esc(row.registrationNo)}</td><td>${esc(row.groupNo)}</td><td>${esc(row.totalScore)}</td></tr>`).join('')}</tbody></table></div></section>`}
window.updateScoreReviewCount=()=>{const boxes=[...document.querySelectorAll('#detailDialog .score-approval-check')],count=boxes.filter(b=>b.checked).length,el=document.getElementById('scoreReviewCount');if(el)el.textContent=`${count} of ${boxes.length} included`;boxes.forEach(b=>b.closest('tr')?.classList.toggle('score-row-excluded',!b.checked))};
window.setAllScoreRows=checked=>{document.querySelectorAll('#detailDialog .score-approval-check').forEach(b=>{b.checked=checked});updateScoreReviewCount()};
window.setScoreReview=async(id,status,section)=>{const endpoint=section==='field-experience'?'field-experience':'project-work',summary=submissions.find(x=>x.id===id),warnings=summary?.[section==='field-experience'?'fieldWarnings':'projectWarnings']||[];if(status==='approved'&&warnings.length&&!confirm(`This submission has ${warnings.length} warning(s). Approve anyway?`))return;let note='';if(['rejected','returned'].includes(status)){const entered=prompt(status==='returned'?'Enter the correction required. This reason will be emailed to the supervisor/examiner:':'Reason / note:','');if(entered===null)return;note=entered.trim();if(status==='returned'&&!note)return alert('Enter the reason or correction required before returning the submission.')}const payload={status,note};if(section==='project-work'){const boxes=[...document.querySelectorAll('#detailDialog .score-approval-check')];if(boxes.length){const included=boxes.filter(b=>b.checked).length;if(status==='approved'&&included===0)return alert('At least one score row must remain checked before this submission can be approved for consolidation.');payload.excludedRowIndexes=boxes.filter(b=>!b.checked).map(b=>Number(b.dataset.sourceIndex)).filter(Number.isInteger);}}const r=await fetch(`${apiBase}/${endpoint}/${id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Could not update status.');if(dialog.open)dialog.close();await load();if(status==='returned'){if(d.emailSent===true)alert('The submission was returned for correction and the reason was emailed to the supervisor/examiner.');else if(d.emailSent===false)alert(`The submission was returned for correction, but the email could not be sent. ${d.emailError||''}`)}};
window.resendScoreCorrectionEmail=async(id,section)=>{const endpoint=section==='field-experience'?'field-experience':'project-work',summary=submissions.find(x=>x.id===id),current=summary?.email||'';const recipient=prompt('Email address to receive the correction notice:',current);if(recipient===null)return;if(!recipient.trim())return alert('Enter an email address.');if(!confirm(`Send the recorded correction reason to ${recipient.trim()}?`))return;const r=await fetch(`${apiBase}/${endpoint}/${id}/resend-return-email`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipientEmail:recipient.trim()})}),d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||'Could not resend the correction email.');if(dialog.open)dialog.close();await load();alert(`Correction email sent to ${d.recipient||recipient.trim()}.`);};

window.showDetail=async id=>{const r=await fetch(`${apiBase}/submissions/${id}`),s=await r.json();if(!r.ok)return alert(s.error||'Record unavailable.');document.getElementById('detailReference').textContent=s.reference||'';let details='',files='',beforeFiles='',afterFiles='';if((s.portalType||'project-work')==='project-work'){const summary=submissions.find(x=>x.id===s.id);const included=(s.reviewScoreRows||[]).filter(row=>row.included!==false).length;details=item('Supervisor / Examiner',s.fullName)+item('Phone',s.phone)+item('Email',s.email)+item('Study Centre(s)',Array.isArray(s.studyCentres)&&s.studyCentres.length?s.studyCentres.join(', '):s.studyCentre)+item('Student Stream',isNonResidentialProject(summary)?'Non-Residential (Regular)':'Distance')+item('Score rows detected',summary?.scoreRows)+item('Rows currently included',`${included} of ${(s.reviewScoreRows||[]).length}`)+item('Status',summary?.projectReviewLabel);files=fileLink(s,'claimForm','Claim form',s.files?.claimForm)+fileLink(s,'reportFile','Report',s.files?.reportFile)+fileLink(s,'scoresFile','Original score sheet',s.files?.scoresFile)+(s.files?.completedWork||[]).map((f,i)=>fileLink(s,'completedWork','Project work',f,i)).join('');beforeFiles=warningPanel(summary,'project');afterFiles=scoreReviewTable(s)+reviewControls(summary,'project','project-work')}
else if(s.portalType==='field-experience'){const summary=submissions.find(x=>x.id===s.id);details=item('Supervisor / Examiner',s.fullName)+item('Phone',s.phone)+item('Email',s.email)+item('Study Centre',s.studyCentre)+item('Score rows',summary?.scoreRows)+item('Status',summary?.fieldReviewLabel);files=fileLink(s,'scoresFile','Original score sheet',s.files?.scoresFile);beforeFiles=warningPanel(summary,'field')+reviewControls(summary,'field','field-experience')}
else if(s.portalType==='dissertation'){const type=s.submissionType||'fresh',label=type==='final'?'Final Dissertation':type==='revised'?'Revised Submission':'Fresh Submission';details=item('Submission Stage',label)+item('Student',s.studentName)+item('Index Number',s.indexNumber)+item('Email',s.email)+item('Programme',s.programme)+item('Supervisor',s.supervisorName)+item('Current Dissertation Title',s.dissertationTopic)+item('Previous-stage Title',s.previousDissertationTopic)+item('Processing Status',s.processingStatus==='returned'?'Returned to Student':'Received')+item('Return Reason',s.returnReason)+item('Returned At',fmt(s.returnedAt));files=fileLink(s,'dissertationFile',label,s.files?.dissertationFile)+fileLinks(s,'reviewerResponses','Reviewer response',s.files?.reviewerResponses)+fileLink(s,'turnitinReport','Plagiarism (Turnitin) report',s.files?.turnitinReport);beforeFiles=can('dissertation','officer')&&s.processingStatus!=='returned'?`<div class="dialog-actions"><button class="btn return" onclick="returnDissertation('${s.id}','${type}')">Return to Student Without Processing</button></div>`:''}
else{details=item('Report Type',(s.reportType||'assessment')==='vetting'?'Vetting Report':'Assessment Report')+item('Assignment Reference',s.assignmentReference)+item('Assessor / Vetter',s.assessorName)+item('Phone',s.phone)+item('Email',s.email)+item('Number of Works',s.workCount||1);beforeFiles=assessmentWorksHtml(s,submissions.find(x=>x.id===s.id))}
document.getElementById('detailBody').innerHTML=`<div class="detail"><div class="detail-grid">${item('Department',s.departmentName)}${item('Submitted',fmt(s.submittedAt))}${details}</div>${beforeFiles}<h3>Submitted files</h3><div class="file-list">${files||''}</div>${afterFiles}${can(s.portalType||'project-work','administrator')?`<div class="dialog-actions"><button class="btn danger" onclick="deleteOneSubmission('${s.id}','submission')">Delete Submission</button></div>`:''}</div>`;dialog.showModal();document.querySelectorAll('#detailDialog .score-approval-check').forEach(b=>b.addEventListener('change',updateScoreReviewCount));updateScoreReviewCount()};
document.getElementById('closeDialog').onclick=()=>dialog.close();

const tabButtons=[...document.querySelectorAll('.admin-tab')],tabPanels=[...document.querySelectorAll('.admin-tab-panel')];function activateAdminTab(tab){const valid=['project','dissertation','assessor'].filter(t=>t==='project'?(can('project-work')||can('field-experience')):can(sectionMap[t]));if(!valid.includes(tab))tab=valid[0]||'project';tabButtons.forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));tabPanels.forEach(p=>p.classList.toggle('hidden',p.dataset.tabPanel!==tab));history.replaceState(null,'',`${location.pathname}${location.search}#${tab}`)}tabButtons.forEach(b=>b.onclick=()=>activateAdminTab(b.dataset.tab));if(search)search.oninput=render;if(dissertationSort)dissertationSort.onchange=renderDissertations;
document.getElementById('logoutBtn').onclick=async()=>{await fetch('/api/admin-logout',{method:'POST'}).catch(()=>{});location.href='/'};
load().then(()=>activateAdminTab((location.hash||'').replace('#','')||'project')).catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend','<div class="fatal">Could not load department submissions.</div>')});
